package com;

// Generated 26 Jan, 2017 7:05:00 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AddOn generated by hbm2java
 */
@Entity
@Table(name = "add_on", catalog = "fleetdb")
public class AddOn implements java.io.Serializable {

	private Integer addonId;
	private String addonName;
	private float addonPrice;

	public AddOn() {
	}

	public AddOn(String addonName, float addonPrice) {
		this.addonName = addonName;
		this.addonPrice = addonPrice;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "addon_id", unique = true, nullable = false)
	public Integer getAddonId() {
		return this.addonId;
	}

	public void setAddonId(Integer addonId) {
		this.addonId = addonId;
	}

	@Column(name = "addon_name", nullable = false, length = 30)
	public String getAddonName() {
		return this.addonName;
	}

	public void setAddonName(String addonName) {
		this.addonName = addonName;
	}

	@Column(name = "addon_price", nullable = false, precision = 12, scale = 0)
	public float getAddonPrice() {
		return this.addonPrice;
	}

	public void setAddonPrice(float addonPrice) {
		this.addonPrice = addonPrice;
	}

}
