package com;

// Generated 25 Jan, 2017 8:29:43 PM by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cars generated by hbm2java
 */
@Entity
@Table(name = "cars", catalog = "fleetdb")
public class Cars implements java.io.Serializable {

	private Integer carId;
	private String carName;
	private String carClass;
	private Float DRate;
	private Float MRate;
	private Float WRate;
	private String imagepath;

	public Cars() {
	}

	public Cars(String carName, String carClass, Float DRate, Float MRate,
			Float WRate, String imagepath) {
		this.carName = carName;
		this.carClass = carClass;
		this.DRate = DRate;
		this.MRate = MRate;
		this.WRate = WRate;
		this.imagepath = imagepath;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "car_id", unique = true, nullable = false)
	public Integer getCarId() {
		return this.carId;
	}

	public void setCarId(Integer carId) {
		this.carId = carId;
	}

	@Column(name = "car_name", length = 30)
	public String getCarName() {
		return this.carName;
	}

	public void setCarName(String carName) {
		this.carName = carName;
	}

	@Column(name = "car_class", length = 20)
	public String getCarClass() {
		return this.carClass;
	}

	public void setCarClass(String carClass) {
		this.carClass = carClass;
	}

	@Column(name = "d_rate", precision = 12, scale = 0)
	public Float getDRate() {
		return this.DRate;
	}

	public void setDRate(Float DRate) {
		this.DRate = DRate;
	}

	@Column(name = "m_rate", precision = 12, scale = 0)
	public Float getMRate() {
		return this.MRate;
	}

	public void setMRate(Float MRate) {
		this.MRate = MRate;
	}

	@Column(name = "w_rate", precision = 12, scale = 0)
	public Float getWRate() {
		return this.WRate;
	}

	public void setWRate(Float WRate) {
		this.WRate = WRate;
	}

	@Column(name = "imagepath", length = 254)
	public String getImagepath() {
		return this.imagepath;
	}

	public void setImagepath(String imagepath) {
		this.imagepath = imagepath;
	}

}
